# These are supported funding model platforms

github: [echobash]
patreon: # Add your Patreon username here (e.g., echobash)
ko_fi: # Add your Ko-fi username here (e.g., echobash)
# liberapay: # Add your Liberapay username here (e.g., echobash)
# open_collective: # Add your Open Collective name here (e.g., devdunia)
custom: ['https://echobash.com', 'https://devdunia.com/support']
